FROM nvidia/cuda:9.0-cudnn7-devel as base

RUN apt-get update && apt-get install -y \
    python3 python3-pip \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6

WORKDIR /app

COPY requirements.common.txt requirements.gpu.txt requirements.lambda.txt /app/
RUN pip3 install -r requirements.gpu.txt -r ./requirements.lambda.txt
