version: '3.7'

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile.${CPU_GPU:-cpu}
    target: base
  volumes:
    - '.:/app:cached'
    - '../in:/in'
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - AWS_SECURITY_TOKEN

services:
  jupyter:
    <<: *app
    ports:
      - '8888:8888'
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root

  dev-cli:
    <<: *app
