version: '3.7'

x-app: &app
  build:
    context: .
    target: base
  volumes:
    - '.:/app:cached'
    - '../in:/in'

services:
  jupyter:
    <<: *app
    ports:
      - '8888:8888'
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root

  dev-cli:
    <<: *app
